pipeline:
  unittests: 
    image: kubam/python-test
    environment:
      - https_proxy=proxy.esl.cisco.com:80
      - http_proxy=proxy.esl.cisco.com:80
    commands: 
      - echo "Building.."
      - cd kubam/app; python -m unittest test.test_db.DBUnitTests
      - cd ../../

