pipeline:
  notify:
    image: vallard/drone-spark
    room: "KUBAM Feedback"
    template: "Starting build {{ build.number }} for {{ repo.owner }}/{{ repo.name }} for {{ build.author }}. Build happening at {{ CI_BUILD_URL }} "
    environment:
      - https_proxy=proxy.esl.cisco.com:80
      - http_proxy=proxy.esl.cisco.com:80
    secrets: [ SPARK_TOKEN ]

  unittests: 
    image: kubam/python-test
    environment:
      - https_proxy=proxy.esl.cisco.com:80
      - http_proxy=proxy.esl.cisco.com:80
    commands: 
      - echo "Building.."
      - pwd
      - ls
      - cd kubam/app; python -m unittest test.test_db.DBUnitTests

  docker:
    image: plugins/docker
    repo: kubam/kubam
    tags: v2
    user: kubam
    secrets: [docker_username, docker_password]
    environment:
      - https_proxy=proxy.esl.cisco.com:80
      - http_proxy=proxy.esl.cisco.com:80
    when: 
      branch: v2.0

  notify:
    image: vallard/drone-spark
    room: "KUBAM Feedback"
    environment:
      - https_proxy=proxy.esl.cisco.com:80
      - http_proxy=proxy.esl.cisco.com:80
    secrets: [ SPARK_TOKEN ]
    when:
      status: [success, failure]
