---

- name: Ensure NTP is installed
  yum:
    name: "{{ item }}"
    state: present
    update_cache: false
    validate_certs: no
  with_items:
    - ntp
    - ntpdate

- name: Copy ntp configuration
  template: 
    src: ../templates/ntp.conf.j2
    dest: /etc/ntp.conf

- name: synctime to NTP server
  shell: service ntpd stop && ntpdate {{ ntp_server }}


- name: Enable OpenVSwitch Kernel Module for Contiv
  command: modprobe openvswitch
  ignore_errors: true
 
- name: Add OpenVSwitch to modules to be loaded for Contiv
  command: echo openvswitch > /etc/modules-load.d/openvswitch.conf 
  ignore_errors: true
  notify:
  - Reload systemd
  - Restart kernel modules

- name: Ensure there is a name for this machine in  /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: "{{ groups.all }}"

# have to make sure NTP is running first or there will be issues with the gpg on some nodes that are drastically out of sync. 
- name: Add Kubernetes yum repo
  yum_repository:
    name: Kubernetes
    description: kubernetes
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    state: present

- name: shutdown firewalld service
  service: 
    name: firewalld 
    state: stopped
  ignore_errors: true

- name: Check to see if CNI tools have been installed. 
  stat:
    path: /opt/cni/bin/cnitool
  register: stat_result


- name: Install Docker
  yum: 
    name: docker

- name: Install Kubeadm and Dependencies
  yum:
    name: "{{ item }}-{{ kubernetes_version }} "
    state: present
    update_cache: true
    validate_certs: no
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  when: stat_result.stat.exists == False

- name: Ensure sysctl is set correctly
  lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    line: net.bridge.bridge-nf-call-iptables = 1
  notify: Restart sysctl
    


- name: Remove existing kubelet args from drop-in unit
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_EXTRA_ARGS'
    state: absent

- name: Remove existing kubelet args from drop-in unit
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^Environment="KUBELET_CGROUP_ARGS'
    state: absent

- name: Use systemd kubelet cgroup driver
  lineinfile:
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    insertafter: '^Environment=\"KUBELET_AUTHZ_ARGS'
    line: 'Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs"'
  notify:
  - Reload systemd
  - Restart kubelet

- name: Enable and start kubeadm services
  systemd: 
    state: started 
    enabled: yes 
    name: '{{ item }}'
  with_items:
    - docker
    - kubelet
    - ntpd

